version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: chadprogress-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ChadDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chadprogress-network
  chadprogress-dev:
    build: .
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/config/dev.yaml"
    command: ["--config_path=${CONFIG_PATH}"]
    depends_on:
      - postgres
    networks:
      - chadprogress-network
  chadprogress-prod:
    build: .
    ports:
      - "8081:8080"  # Другой порт, чтобы не конфликтовало
    environment:
      CONFIG_PATH: "/config/prod.yaml"
    command: ["--config_path=${CONFIG_PATH}"]
    depends_on:
      - postgres
    networks:
      - chadprogress-network
  chadprogress-local:
    build: .
    ports:
      - "8082:8080"  # Уникальный порт
    environment:
      CONFIG_PATH: "/config/local.yaml"
    command: ["--config_path=${CONFIG_PATH}"]
    depends_on:
      - postgres
    networks:
      - chadprogress-network

networks:
  chadprogress-network:
    driver: bridge

volumes:
  postgres_data: