version: '3.8'

services:
  cp-db:
    image: postgres:latest
    container_name: chadprogress-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ChadDB
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network
  chadprogress-dev:
    build: .
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/config/dev.yaml"
    command: ["--config_path=${CONFIG_PATH}"]
    depends_on:
      - cp-db
    networks:
      - shared-network
  chadprogress-prod:
    build: .
    ports:
      - "8081:8080"
    environment:
      CONFIG_PATH: "/config/prod.yaml"
    command: ["--config_path=${CONFIG_PATH}"]
    depends_on:
      - cp-db
    networks:
      - shared-network
  chadprogress-local:
    build: .
    ports:
      - "8082:8080"
    environment:
      CONFIG_PATH: "/config/local.yaml"
    command: ["--config_path=${CONFIG_PATH}"]
    depends_on:
      - cp-db
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  postgres_data: