env: "dev"
http_server:
  host: "chadprogress-dev"
  port: "8080"
  timeout: 4s
  idle_timeout: 60s
db:
  username: "postgres"
  host: "cp-db"
  port: "5432"
  dbname: "ChadDB"
  sslmode: "disable"
auth_client:
  baseurl: "http://jwt-auth-service-local:8000"