env: "local"
http_server:
  host: "chadprogress-local"
  port: "8082"
  timeout: 4s
  idle_timeout: 60s
db:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "ChadDB"
  sslmode: "disable"
auth_client:
  baseurl: "http://127.0.0.1:8001"